services:
  message-exchange.api:
    image: message-exchange.api
    build:
      context: .
      dockerfile: MessageExchange.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    container_name: message-exchange-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
  seq:
    image: datalust/seq:latest
    container_name: message-exchange-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    restart: always
    volumes:
      - seq:/data

volumes:
  postgres:
    name: message-exchange-pgdata
  seq:
    name: seq-data